##################################################################################
# Cloudify AWS EC2 built in types and plugins definitions.
##################################################################################

plugins:
  aws:
    executor: central_deployment_agent
    source: https://github.com/cloudify-cosmo/cloudify-aws-plugin/archive/master.zip # { tag }

node_types:
  cloudify.aws.nodes.Instance:
    derived_from: cloudify.nodes.Compute
    properties:
      use_external_resource:
        description: >
          Indicate whether the resource exists or if Cloudify should create the resource.
        type: boolean
        default: false
      resource_id:
        description: >
          If this is an existing resource, you should provide the ID of the resource in Amazon AWS.
          If this a new
        type: string
        default: ''
      image_id:
        description: >
          The ID of the AMI image in your Amazon account.
        type: string
      instance_type:
        description: >
          The instance's size.
        type: string
      parameters:
        description: >
          The key value pair parameters allowed by Amazon API to the
          ec2.connection.EC2Connection.run_instances command. It should be mentioned that
          although this field is listed as optional. A non-trivial use case requires
          that both the key_name parameter and the security_groups parameter be specified. 
    interfaces:
      cloudify.interfaces.lifecycle:
        create: aws.ec2.instance.run_instances
        start:
          implementation: aws.ec2.instance.start
          inputs:
            retry_interval:
              description: How many seconds between state checks.
              type: integer
              default: 20
        stop:
          implementation: aws.ec2.instance.stop
          inputs:
            retry_interval:
              description: How many seconds between state checks.
              type: integer
              default: 20
        delete:
          implementation: aws.ec2.instance.terminate
          inputs:
            retry_interval:
              description: How many seconds between state checks.
              type: integer
              default: 20
      cloudify.interfaces.validation:
        creation:
          implementation: aws.ec2.instance.creation_validation

  cloudify.aws.nodes.ElasticIP:
    derived_from: cloudify.nodes.VirtualIP
    properties:
      use_external_resource:
        description: >
          Indicate whether the resource exists or if Cloudify should create the resource.
        type: boolean
        default: false
      resource_id:
        description: >
          Either the name or ID of the resource in Cloudify. If this is an existing
          resource, you should provide the name or the ID of the resource in Amazon AWS.
        type: string
        default: ''
    interfaces:
      cloudify.interfaces.relationship_lifecycle:
        establish: aws.ec2.elasticip.allocate
        unlink: aws.ec2.elasticip.release
      cloudify.interfaces.validation:
        creation: aws.ec2.elasticip.creation_validation

  cloudify.aws.nodes.SecurityGroup:
    derived_from: cloudify.nodes.SecurityGroup
    properties:
      use_external_resource:
        description: >
          Indicate whether the resource exists or if Cloudify should create the resource.
        type: boolean
        default: false
      resource_id:
        description: >
          Either the name or ID of the resource in Cloudify. If this is an existing
          resource, you should provide the name or the ID of the resource in Amazon AWS.
        type: string
        default: ''
      description:
        description: >
          The description field that is required for every security group that you create
          in Amazon.
        type: string
        default: ''
      rules:
        default: []
        description: >
          A list of rules, which are each a dictionary of key value pairs with the required
          keys: ip_protocol (string), from_port (integer), to_port (integer), and 
          cidr_ip (string).
    interfaces:
      cloudify.interfaces.lifecycle:
        create: aws.ec2.securitygroup.create
        delete: aws.ec2.securitygroup.delete
      cloudify.interfaces.validation:
        creation: aws.ec2.securitygroup.creation_validation
      cloudify.interfaces.securitygroup:
        add_rule: aws.ec2.securitygroup.authorize

  cloudify.aws.nodes.KeyPair:
    derived_from: cloudify.nodes.Root
    properties:
      use_external_resource:
        description: >
          Indicate whether the resource exists or if Cloudify should create the resource.
        type: boolean
        default: false
      resource_id:
        description: >
          Either the name or ID of the resource in Cloudify. If this is an existing
          resource, you should provide the name or the ID of the resource in Amazon AWS.
        type: string
        default: ''
      private_key_path:
        description: >
          The path where the key should be saved on the machine. If this is a bootstrap
          process, this refers to the local computer. If this will run on the manager,
          this will be saved on the manager.
        type: string
        default: ''
    interfaces:
      cloudify.interfaces.lifecycle:
        create: aws.ec2.keypair.create
        delete: aws.ec2.keypair.delete
      cloudify.interfaces.validation:
        creation: aws.ec2.keypair.creation_validation

relationships:
  cloudify.aws.relationships.instance_connected_to_elastic_ip:
    derived_from: cloudify.relationships.connected_to
    source_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        establish: aws.ec2.elasticip.associate
        unlink: aws.ec2.elasticip.disassociate

  cloudify.aws.relationships.instance_connected_to_keypair:
    derived_from: cloudify.relationships.connected_to

  cloudify.aws.relationships.instance_connected_to_security_group:
    derived_from: cloudify.relationships.connected_to
