---
project_exclusion_list:
  exclusion_folders:
    - .drp
    - .github
    - examples
    - cloudify_aws/s3/tests
  #   - test
  #   - jenkins
  #   - buildroot
  #   - buildroot
  exclusion_file_paths:
    - Makefile
