---
project_exclusion_list:
  exclusion_folders:
    - .drp
    - .github
    - examples
    - Makefile
    - cloudify_aws/s3/tests
  #   - test
  #   - jenkins
  #   - buildroot
  #   - buildroot
  # exclusion_file_paths:
  #   - package/tpm2-tools/tpm2-tools.hash
